# Generated by Django 4.0 on 2022-01-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MakeDealOU',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='MakeDealU',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Product',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_Id',
            field=models.CharField(max_length=1200),
        ),
    ]
