# Generated by Django 4.0 on 2022-01-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_makedealou_product_makedealu_product_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='MakeDealOU',
        ),
        migrations.RemoveField(
            model_name='product',
            name='MakeDealU',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product',
        ),
    ]
