# Generated by Django 4.0 on 2022-01-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_makedealou_remove_product_makedealu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=1200),
        ),
    ]
