# Generated by Django 4.0 on 2022-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Phone',
            field=models.CharField(max_length=1200),
        ),
    ]
