# Generated by Django 4.0 on 2021-12-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtable',
            name='MakeDeal',
            field=models.BooleanField(default=False),
        ),
    ]
