# Generated by Django 4.0 on 2022-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_makedeal_matchtable_makedealou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtable',
            name='Product',
            field=models.BooleanField(default=False),
        ),
    ]
