# Generated by Django 4.0 on 2022-01-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_matchtable_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='Product',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
