# Generated by Django 4.0 on 2022-01-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_matchtable_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchtable',
            name='MakeDealOU',
        ),
        migrations.RemoveField(
            model_name='matchtable',
            name='MakeDealU',
        ),
        migrations.RemoveField(
            model_name='matchtable',
            name='Product',
        ),
    ]
