# Generated by Django 4.0 on 2022-01-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_matchtable_makedealou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtable',
            name='MakeDealOU',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchtable',
            name='MakeDealU',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchtable',
            name='Product',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
