# Generated by Django 4.0 on 2022-01-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_matchtable_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='ProductImg',
            field=models.ImageField(upload_to=''),
        ),
    ]
