# Generated by Django 4.0 on 2022-01-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_matchtable_productimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Add',
            new_name='Dashboard',
        ),
        migrations.RemoveField(
            model_name='role',
            name='Delete',
        ),
        migrations.RemoveField(
            model_name='role',
            name='Edit',
        ),
    ]
