# Generated by Django 4.0 on 2022-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_add_role_dashboard_remove_role_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=1200),
        ),
    ]
